# Documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
# For openrefine java deps
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 15
  ignore:
    - dependency-name: com.thoughtworks.xstream:xstream
      versions:
      - "> 1.4.12"
      - "< 2"
    - dependency-name: "org.eclipse.jetty:jetty-*"
      versions:
        - ">= 10.0.0"
    - dependency-name: "formatter-maven-plugin"
    - dependency-name: "impsort-maven-plugin"
      versions:
        - ">= 1.10.0" # Requires Java 17 and we build with Java 11 for distribution
  target-branch: "master"
   
# For main webapp
- package-ecosystem: "npm"
  directory: "main/webapp"
  schedule:
    interval: "weekly"
# For github actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    actions:
       patterns:
         - "*"
# For cypress test_suite
- package-ecosystem: "npm"
  directory: "main/tests/cypress"
  schedule:
    interval: "weekly"
  groups:
    cypress:
      patterns:
        - "*"
