version: 1.0.{build}

services:
- mysql
- postgresql96

init:
- cmd: java -version 2>&1 | find "version"

clone_depth: 5
skip_branch_with_pr: true

environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  MAVEN_HOME: C:\Program Files (x86)\Apache\Maven

matrix:
  fast_finish: true

build: off

# scripts to run before test
before_test:
- cmd: echo Running scripts before build...
- cmd: |-
    PATH=C:\Program Files\PostgreSQL\9.6\bin\;C:\Program Files\MySQL\MySQL Server 5.7\bin\;%PATH%
    SET MYSQL_PWD=Password12!
    mysql -u root --password=Password12! -e "create database test_db;"
    mysql -u root test_db --password=Password12! < extensions\database\tests\conf\travis-mysql.sql
    echo "localhost:*:test_db:postgres:Password12!" > C:\Program Files\PostgreSQL\9.6\pgpass.conf
    echo "localhost:*:test_db:postgres:Password12!" > pgpass.conf
    echo "localhost:*:test_db:postgres:Password12!" > %userprofile%\pgpass.conf
    SET PGPASSFILE=C:\Program Files\PostgreSQL\9.6\pgpass.conf
    SET PGPASSWORD=Password12!
    SET PGUSER=postgres
    createdb test_db
    psql -U postgres test_db < extensions\database\tests\conf\travis-pgsql.sql

    copy extensions\database\tests\conf\appveyor_tests.xml extensions\database\tests\conf\tests.xml
    copy packaging\travis_pom.xml packaging\pom.xml
- cmd: |-
    mvn process-resources
    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

test_script:
- cmd: echo Running test_script...
- cmd: >-
    echo PATH is:

    path

    refine test

on_failure:
- cmd: |-
    dir

cache:
  - C:\Users\appveyor\.m2

